spring.application.name=conectorpedidoscompra

# --- Configuração Ativa: Banco em Memória (H2) ---
spring.datasource.url=jdbc:h2:mem:v360db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# --- Configuração Futura: PostgreSQL ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/v360db
# spring.datasource.username=seu_usuario
# spring.datasource.password=sua_senha
# spring.jpa.hibernate.ddl-auto=update
